---
sssd_ldap_uri: "{{ lookup('env', 'LDAP_URI') }}"
sssd_ldap_search_base: "{{ lookup('env', 'LDAP_SEARCH_BASE') }}"
sssd_ldap_user_search_base: "ou=users,{{ lookup('env', 'LDAP_SEARCH_BASE') }}"
ldap_group_search_base: "{{ lookup('env', 'LDAP_SEARCH_BASE') }}"
sssd_ldap_access_filter: "memberOf=cn=sysadmin,ou=users,{{ lookup('env', 'LDAP_SEARCH_BASE') }}"
sssd_ldap_bind_dn: "{{ lookup('env', 'LDAP_BIND_DN') }}"
sssd_ldap_auth_token: "{{ lookup('env', 'LDAP_BIND_AUTH_TOKEN') }}"

sssd_ldap_name: ldap
sssd_ldap_ssh_public_key: sshPublicKey
sssd_ldap_sudo_groups:
  - name: sysadmin
    spec: ALL=(ALL:ALL) NOPASSWD:ALL
