---
- name: SSSD LDAP | Configure | SSH | AuthorizedKeysCommand
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^AuthorizedKeysCommand "
    line: AuthorizedKeysCommand /usr/bin/sss_ssh_authorizedkeys
    state: present
  notify:
    - SSSD LDAP | Restart SSH

- name: SSSD LDAP | Configure | SSH | AuthorizedKeysCommandUser
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^AuthorizedKeysCommandUser "
    line: AuthorizedKeysCommandUser root
    state: present
  notify:
    - SSSD LDAP | Restart SSH

- name: SSSD LDAP | Configure | SSH | PubkeyAuthentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PubkeyAuthentication "
    line: PubkeyAuthentication yes
    state: present
  notify:
    - SSSD LDAP | Restart SSH

- name: SSSD LDAP | Configure | SSH | PermitRootLogin
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin "
    line: PermitRootLogin no
    state: present
  notify:
    - SSSD LDAP | Restart SSH

- name: SSSD LDAP | Configure | SSH | PAM Make Homedir
  ansible.builtin.lineinfile:
    path: /etc/pam.d/common-session
    regexp: "^.*pam_mkhomedir.so"
    insertafter: "^session\trequired\tpam_unix.so"
    line: session required pam_mkhomedir.so skel=/etc/skel/ umask=0077
    state: present
