---
packages_list:
  - wget
  - curl
  - git
  - vim
  - python3
  - python3-venv
  - python3-pip
  - open-iscsi
  - nfs-common
  - apt-transport-https
  - dirmngr
  - htop
  - btop
  - tmux
  - ca-certificates
  - gnupg
  - lsb-release
  - jq
  - unzip
