---
galaxy_info:
  namespace: muhlba91
  role_name: sssd_ldap
  description: Role to install and setup the SSSD using LDAP
  author: Daniel Muehlbachler-Pietrzykowski <daniel.muehlbachler@niftyside.io>

  license: GPL-2.0-or-later

  min_ansible_version: 7.0.0

  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - sssd
    - ldap

dependencies: []
