---
- name: SSSD LDAP | Restart SSH
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: SSSD LDAP | Restart SSSD
  ansible.builtin.systemd:
    name: sssd
    state: restarted
    enabled: true
